Верстка главной страницы сайта Техномарт
htmlacademy-htmlcss/1587651-technomart-29 pull request #2
Opened 2020-09-12 12:40 UTC by maxymasang

2020-09-12 15:39 UTC, dean992008 requested changes

2020-09-12 15:39 UTC, dean992008 commented on blank.html
> +<!DOCTYPE html>
Этой страницы буть не должно. Если нужно сделать сылку на виртуальную страницу в нее даостаточно поставить `#`

2020-09-12 15:39 UTC, dean992008 commented on img/Вконтакте.svg
> +<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
Названия файлов должны быть латиницей и все буквы маленкие. https://up.htmlacademy.ru/htmlcss/29/criteries#b14

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +  <header>
Нет логотипа.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +    <div>
Поиск нужно будет обернуть в form. Но пока ее не нужно делать, формы мы будет мделать в 4 задании.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <p><i>Интернет-магазин<br>
Тег `i` и `br` не нужно делать в HTML, это задача CSS.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <p>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
Здесь можно использовать тег adress

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <a href="blank.html">Войти</a>
Сылки на страницы которых нет можно писать как `#`

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +    <div>
Это div не нужен, вместо него можно использовать `nav`

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +          <li><a href="index.html">Техномарт</a></li>
Я так понимаю это лого. Его нужно удалить из главного меню и поставить в начало header. Также лого это картинка.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +        <li>
Слайден можно сделать ячейкой предидущего списка, так будет удобно сделать сетку на гридах.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +          <h3>Перфораторы</h3>
Слайда в слоях 2, их нужно разметить и обернуть в список.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +          <p><a href="catalog.html">Открыть каталог</a></p>
Сылка должна быть внутри слайда, стрелки и пагинация рядом со списком.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +          <button type="button">25500 Р.</button>
Это не кнопки, просто стилизованый текст.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <h3>Доставка</h3>
В слоях есть `Гарантия` и `Кредит` из тоже нужно разметить и вместе с Доставкой обернуть в список.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <img src="img/delivery.png" width="468" height="261" alt="Доставка">
Это декоративная картинка. Пока ее нужно убрать, потом добавим через CSS

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +      <img src="img/map.png" width="300" height="158" alt="Карта">
карту нужно обернуть в сылку, сылка должна вести на сервис карт.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +  <footer>
Футер лучше разбить на 3 сторки или 3 секции, так потом будет удобнее стилизовать.

2020-09-12 15:39 UTC, dean992008 commented on index.html
> +        <a href="https://htmlacademy.ru">htmlacademy.ru</a>
Сылка должна вести на страницу курса, смотри: https://up.htmlacademy.ru/htmlcss/29/project/technomart#technomart-3-5
Также сылки на другой сайт, нужно открывать в новой вкладке.

2020-09-12 16:23 UTC, maxymasang commented on index.html
> +  <header>
На макете сайта в фигме, логотип техномарт написан текстом, а если открыть изображение открывается просто зеленая подложка. Его все равно нужно оформлять как <img>?

2020-09-12 16:23 UTC, maxymasang commented on index.html
> +    <div>
Пока что его просто сделать как <a href="#">?

2020-09-12 16:28 UTC, maxymasang commented on index.html
> +          <li><a href="index.html">Техномарт</a></li>
Логотип не относится к главной навигации сайта? На лекции об этом говорилось, и упоминали что логотип относится к навигации, но может располагаться в другой части сайта.

2020-09-12 16:49 UTC, maxymasang commented on index.html
> +      <h3>Доставка</h3>
В этих текстах, если не использовать тег br, пускай идет сейчас сплошным текстом, или разбить его как там но все строки на теги p?

2020-09-12 16:59 UTC, dean992008 commented on index.html
> +  <header>
Да, логика какая: между загрузкой страницы и шрифта есть небольшой зазор во времени и если сделать лого текстом то он будет искажается в это время, а это не допустимо со стороны маркетинга и будет просто считаться багом, поэтому лого делают картинкой чтобы гарантировать что оно будет выглядеть именно так как нарисовано в макете.

2020-09-12 17:01 UTC, dean992008 commented on index.html
> +    <div>
Пока достоинства написать комментарий. 
<!-- TODO: Сделать форму поиска. -->

2020-09-12 17:02 UTC, dean992008 commented on index.html
> +          <li><a href="index.html">Техномарт</a></li>
И да и нет. Конкретно в данном случае как ты планируешь сделать чтобы он оказался там где должен быть?

2020-09-12 17:03 UTC, dean992008 commented on index.html
> +      <h3>Доставка</h3>
Пока сплошным, мы пока о внешнем виде не говорим, только симантика, а потом можно будет подогнать с помощью CSS, задав нужную ширину.

2020-09-13 11:23 UTC, dean992008 commented on index.html
> +  <header>
Страница не должна ссылаться сама на себя нужно убрать `href` из ссылки того.

2020-09-13 11:25 UTC, dean992008 commented on index.html
> +        <li>
Слайдер должен быть вложены списком.

2020-09-13 13:03 UTC, merged